version: '3'

tasks:
  build:
    desc: "Build Docker image for local development environment"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml build {{.CLI_ARGS}}

  start:
    desc: "Start the Docker containers"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml up {{.CLI_ARGS}}

  stop:
    desc: "Stops the Docker containers"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml stop

  down:
    desc: "Down the Docker containers"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml down

  startapp:
    desc: "Creates a new App at apps/<app_name>"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml exec web mkdir apps/{{.CLI_ARGS}}
      - docker-compose -f docker/docker-compose.local.yaml exec web python manage.py startapp {{.CLI_ARGS}} apps/{{.CLI_ARGS}}

  manage:
    desc: "Run a Django management command"
    cmds:
      - docker-compose -f docker/docker-compose.local.yaml exec web python manage.py {{.CLI_ARGS}}
