version: '3'

env:
  COMPOSE: docker compose -f docker/docker-compose.yaml

tasks:
  compose-*:
    desc: "Run a docker compose command like: task compose-up -- -d"
    vars:
      COMMAND: '{{index .MATCH 0}}'
    cmds:
      - $COMPOSE {{.COMMAND}} {{.CLI_ARGS}}

  manage-startapp:
    desc: "Creates a new app <app_name> at apps/<app_name>"
    cmds:
      - $COMPOSE exec web mkdir apps/{{.CLI_ARGS}}
      - $COMPOSE exec web python manage.py startapp {{.CLI_ARGS}} apps/{{.CLI_ARGS}}

  manage-*:
    desc: "Run a manage.py command like: task manage-migrate -- <app>"
    vars:
      COMMAND: '{{index .MATCH 0}}'
    cmds:
      - $COMPOSE exec web python manage.py {{.COMMAND}} {{.CLI_ARGS}}

  poetry-*:
    desc: "Run a poetry command like: task poetry-add -- <package>"
    vars:
      COMMAND: '{{index .MATCH 0}}'
    cmds:
      - $COMPOSE exec web poetry {{.COMMAND}} {{.CLI_ARGS}}
