version: '3'

tasks:
  build-*:
    desc: "Build Docker image for local development environment"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml build {{.CLI_ARGS}}

  start-*:
    desc: "Start the Docker containers"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml up {{.CLI_ARGS}}

  stop-*:
    desc: "Stops the Docker containers"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml stop

  down-*:
    desc: "Down the Docker containers"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml down

  startapp-*:
    desc: "Creates a new App at apps/<app_name>"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml exec web mkdir apps/{{.CLI_ARGS}}
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml exec web python manage.py startapp {{.CLI_ARGS}} apps/{{.CLI_ARGS}}

  manage-*:
    desc: "Run a Django management command"
    vars:
      ENV: '{{index .MATCH 0}}'
    cmds:
      - docker-compose -f docker/docker-compose.{{.ENV}}.yaml exec web python manage.py {{.CLI_ARGS}}
