services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn django_base.wsgi --bind 0.0.0.0:8000 --workers=2;
      "
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    environment:
      - DJANGO_SETTINGS_MODULE=django_base.settings.prod
    env_file:
      - ../.env
    expose:
      - 8000
    networks:
      - nginx-network
      - postgres-network

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - nginx-network
    depends_on:
      - web

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ../prometheus:/etc/prometheus/
      - prometheus_data:/prometheus
    depends_on:
      - web

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true
    depends_on:
      - prometheus

volumes:
  grafana_data:
  prometheus_data:
  static_volume:
  media_volume:

networks:
  nginx-network:
    driver: bridge
