services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: >
      sh -c "
        python manage.py migrate &&
        gunicorn django_base.wsgi --workers=2;
      "
    volumes:
      - ../:/code
    environment:
      - DJANGO_SETTINGS_MODULE=django_base.settings.production
    env_file:
      - ../.env
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ../prometheus:/etc/prometheus/
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_JSON_ENABLED=true

volumes:
  grafana_data:
  prometheus_data:
