services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn django_base.wsgi --bind 0.0.0.0:8000 --workers=2;
      "
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    environment:
      - DJANGO_SETTINGS_MODULE=django_base.settings.prod
    env_file:
      - ../.env
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build: ../nginx
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
